Increase the URL length on API and Samplify
researchnow/dotnet-samplifyapi-client pull request #18
Opened 2020-08-03 11:59 UTC by ssi-hu-janos-pelsoczi

set max url length to 2000

2020-08-03 23:02 UTC, andyshipman approved these changes
Looks good to me

2020-08-10 21:43 UTC, caseylucas requested changes
see comments

2020-08-10 21:43 UTC, caseylucas commented on SamplifyAPIClient/LineItem.cs
> +        public int LastAcceptedLOI { get; set; }
This change appears to be unrelated to url length. Unless this change is related, can you remove it?

2020-08-10 21:43 UTC, caseylucas commented on SamplifyAPIClient/Project.cs
> +    }
Remove unrelated change.

2020-08-11 10:58 UTC, ssi-hu-janos-pelsoczi commented on SamplifyAPIClient/Project.cs
> +    }
Not changed this part, only change line 181: Validator.ValidateUrlLength(this.SurveyURL);

2020-08-11 22:46 UTC, caseylucas approved these changes
@ssi-hu-janos-pelsoczi I put back the original line endings. If you agree with the changes as they stand, please merge PR.

2020-08-12 12:36 UTC, merged